# =========================
# APPLICATION
# =========================
spring.application.name=Orose

# =========================
# DATABASE (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/orose
spring.datasource.username=postgres
spring.datasource.password=j
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de connexion (IMPORTANT pour éviter "connection closed")
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate 6 → dialect optionnel (tu peux même l'enlever)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT: évite certains accès metadata instables
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false

# ⚠️ À éviter en production (mais OK en dev)
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html

# =========================
# SERVER
# =========================
server.port=8080