TRUNCATE TABLE
    inventaire,
    alerte,
    mouvement_stock_crevette,
    lot_crevette,
    recolte_declaration,
    traitement_medicament_lot,
    traitement,
    incident_sanitaire,
    mouvement_stock_medicament,
    entree_stock_medicament,
    medicament,
    distribution_nourriture_lot,
    distribution_nourriture,
    mouvement_stock_aliment,
    entree_stock_aliment,
    aliment,
    creneau_horaire,
    suivi_hebdo_bassin,
    cycle_bassin_assoc,
    cycle,
    evolution_hebdo_espece,
    espece_crevette,
    histo_statut_bassin
RESTART IDENTITY CASCADE;